#!/bin/bash

echo "🔥 Firebase Admin SDK Setup Guide"
echo "=================================="
echo ""
echo "📋 Follow these steps to get your Firebase Service Account:"
echo ""
echo "1️⃣  Go to Firebase Console:"
echo "   https://console.firebase.google.com"
echo ""
echo "2️⃣  Select your project (kmtsys or similar)"
echo ""
echo "3️⃣  Click ⚙️ Settings (top left) → Project Settings"
echo ""
echo "4️⃣  Go to 'Service Accounts' tab"
echo ""
echo "5️⃣  Click 'Generate New Private Key' button"
echo ""
echo "6️⃣  Download the JSON file"
echo ""
echo "7️⃣  Copy the ENTIRE content of that JSON file"
echo ""
echo "8️⃣  Add it to your .env.local file:"
echo ""
echo "=================================="
echo "EXAMPLE .env.local format:"
echo "=================================="
echo ""
echo 'FIREBASE_SERVICE_ACCOUNT={"type":"service_account","project_id":"YOUR_PROJECT","private_key_id":"xxx","private_key":"-----BEGIN PRIVATE KEY-----\\nXXX\\n-----END PRIVATE KEY-----\\n","client_email":"firebase-adminsdk-xxx@YOUR_PROJECT.iam.gserviceaccount.com","client_id":"xxx","auth_uri":"https://accounts.google.com/o/oauth2/auth","token_uri":"https://oauth2.googleapis.com/token","auth_provider_x509_cert_url":"https://www.googleapis.com/oauth2/v1/certs","client_x509_cert_url":"xxx"}'
echo ""
echo "=================================="
echo "⚠️  IMPORTANT:"
echo "=================================="
echo "- Copy the JSON as ONE LINE"
echo "- Keep all the \\n in the private_key"
echo "- Don't add spaces or line breaks"
echo "- Add to .env.local (NOT .env - it's in .gitignore)"
echo ""
echo "🧪 After adding, test with:"
echo "   node test-firebase-push.js"
echo ""
